name: 'Validate JSON file'
description: 'Validates JSON file against schema.'

inputs:
  environment:
    required: true
    description: 'TBD'
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - id: validate
      name: Validate JSON file
      shell: pwsh
      run: ${{ github.action_path }}\scripts\Test-JsonConfig.ps1 -Environment '${{ inputs.environment }}'